# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: SimpleMvvm/SimpleMvvm/SimpleMvvm.csproj
        regex: '^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)$'
    - name: Show version
      run: echo ${{ steps.package_version.outputs.version }}.${{github.run_number}}
    - name: Install MAUI workload
      run: dotnet workload install maui
      working-directory: SimpleMvvm
    - name: Restore workload dependencies
      run: dotnet workload restore
      working-directory: SimpleMvvm
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SimpleMvvm
    - name: Build
      run: dotnet build --no-restore
      working-directory: SimpleMvvm
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: SimpleMvvm
    - name: Set Nuget Source
      run: dotnet nuget add source --username proxna --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/proxna/index.json"
    - name: Create Package
      run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.package_version.outputs.version }}.${{github.run_number}}
      working-directory: SimpleMvvm/SimpleMvvm
    - name: Publish Package
      run: dotnet nuget push "bin/Release/SimpleMvvm.${{ steps.package_version.outputs.version }}.${{github.run_number}}.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
      working-directory: SimpleMvvm/SimpleMvvm
